@{
    'Load-PSProfile'         = 'Import-PSProfile'
    'Refresh-PSProfile'      = 'Update-PSProfileConfig'
    'Creds'                  = 'Get-MyCreds'
    'Save-Prompt'            = 'Add-PSProfilePrompt'
    'Get-Prompt'             = 'Get-PSProfilePrompt'
    'Edit-Prompt'            = 'Edit-PSProfilePrompt'
    'Switch-Prompt'          = 'Switch-PSProfilePrompt'
    'Remove-Prompt'          = 'Remove-PSProfilePrompt'
    'Copy-DynamicParameters' = 'Copy-Parameters'
    'def'                    = 'Get-Definition'
    'open'                   = 'Open-Item'
    'push'                   = 'Push-Path'
    'pop'                    = 'Pop-Path'
    'cln'                    = 'Enter-CleanEnvironment'
    'bld'                    = 'Start-BuildScript'
    'syntax'                 = 'Format-Syntax'
    'path'                   = 'Get-LongPath'
}
